import Navigation from '@/app/components/navigations/Navigation';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
// import { dark } from '@clerk/themes';
import Providers from './providers/AppProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang='en' className='min-h-screen'>
				<body className={`grid place-items-center ${inter.className}`}>
					<Providers>
						<Navigation />
						{children}
					</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
